spark:
  app:
    name: "FraudDetectionStreaming-Docker"
  master: "local[*]"  
  config:
    "spark.sql.adaptive.enabled": "true"
    "spark.sql.adaptive.coalescePartitions.enabled": "true"
    "spark.serializer": "org.apache.spark.serializer.KryoSerializer"
    "spark.streaming.backpressure.enabled": "true"
    "spark.streaming.kafka.consumer.cache.enabled": "false"
    
  kafka:
    bootstrap.servers: "kafka:9092" 
    startingOffsets: "latest"
    failOnDataLoss: "false"